### ISSUE TITLE
multichannel error?

### ISSUE THREAD

**Issue by alexzapatka** [Mechazawa/REDBetter-crawler#24]
```
Traceback (most recent call last):
  File "./redactedbetter", line 231, in <module>
    main()
  File "./redactedbetter", line 182, in main
    if transcode.is_multichannel(flac_dir):
  File "/home/gimp/REDBetter-crawler/transcode.py", line 102, in is_multichannel
    return any(flac.info.channels > 2 for flac in flacs)
  File "/home/gimp/REDBetter-crawler/transcode.py", line 102, in <genexpr>
    return any(flac.info.channels > 2 for flac in flacs)
  File "/home/gimp/REDBetter-crawler/transcode.py", line 101, in <genexpr>
    flacs = (mutagen.flac.FLAC(flac_file) for flac_file in locate(flac_dir, ext_matcher('.flac')))
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_util.py", line 158, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_util.py", line 129, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/flac.py", line 789, in load
    self.__check_header(fileobj, filething.name)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/flac.py", line 904, in __check_header
    header = fileobj.read(4)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/flac.py", line 70, in read
    size, len(data)))
mutagen.flac.error: file said 4 bytes, read 0 bytes
```

**Comment by Mechazawa** [comment]
Fixed in https://github.com/Mechazawa/REDBetter-crawler/commit/ec6228bfeb9a6df6d6686215c6cd372d03ec050e

**Comment by Mechazawa** [comment]
This means there is an error in the flac file
